language: cpp
compiler: clang

script:
- cmake .
- cmake --build . --target async

deploy:
- provider: script
  skip_cleanup: true
  script:
  - curl -T async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usmart-roger:$BINTRAY_API_KEY "https://api.bintray.com/content/smart-roger/Otus_cpp/async/$TRAVIS_BUILD_NUMBER/async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 
